{{- if .Values.ingress.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- $upper := . -}}
    {{- range .Values.ingress.hosts }}
    - http:
        paths:
          {{- range .paths }}
          - path: {{ tpl .path $upper | quote }}
            pathType: {{ .pathType }}
            backend: 
              serviceName: {{ .serviceName  }}
              servicePort: {{ .servicePort  }}
          {{- end }}
      {{ if .host }}
      host: {{ tpl .host $upper | quote }}
      {{ end}}
    {{- end }}
  {{- end }}
